[build-system]
requires = ["setuptools>=61", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pipesay"
dynamic = ["version"]
description = "一个用管道处理句子的趣味输出工具"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-cowsay",
    "desktop_notifier",
    "jieba",
    "openai",
    "pyaml",
    "requests",
    "translators",
    "urllib3"
]

[project.scripts]
pipesay = "pipesay.main:main"

[tool.setuptools_scm]
local_scheme = "no-local-version"